### ISSUE TITLE
How is the cron supposed to work?

### ISSUE THREAD

**Issue by miloskroulik** [rodrigoreyes79/ttlogger#1]
I wonder, how the cron functionality is supposed to work. Do I have to run app as daemon? Will app pop over other windows on specified time?

**Comment by rodrigoreyes79** [comment]
Hi, Milos. The cron simply adds a new date to the date selector and selects it. You don't have to run the app as a demon (just start it and keep it running in the background) and it will not "pop over" the other windows as it is right now, but I think that may be a good idea. If you are interested in that, I can make it pop over.

Thanks for trying ttlogger :)
