### ISSUE TITLE
Can't type into text box

### ISSUE THREAD

**Issue by csu** [rodrigoreyes79/ttlogger#2]
When I launch it with `nw .` in `src/`, it opens the window and I can click on the elements, but when I type, all the input goes into my iTerm window. How can I fix this?

**Comment by csu** [comment]
Oh yeah, I forgot to mention, I'm on Mac OS X 10.10 and using iTerm 2.

**Comment by rodrigoreyes79** [comment]
Hi, csu. I don't have a Mac to test it on yet, but I will get one in the next couple of weeks. I will test it then and will let you know once the bug is fixed.

**Comment by rodrigoreyes79** [comment]
csu

Got the time to test it on my mac now. It seems to be working just fine. I installed nwjs.app, then went into the src folder and run the following: /Applications/nwjs.app/Contents/MacOS/nwjs .

Please let me know if you are still having issues. In the meantime, I am going to mark this issue as closed.
